### ISSUE TITLE
miniconda installation on cluster

### ISSUE THREAD

**Issue by DHekstra** [Hekstra-Lab/room-of-requirement#1]
see https://conda.io/projects/conda/en/latest/user-guide/install/linux.html for slightly updated instructions on the miniconda install. (also my first issue submitted, albeit very minor:)

**Comment by JBGreisman** [comment]
I might be missing something -- what is the difference?

**Comment by JBGreisman** [comment]
I updated the section. It is worth noting that the difference between `bash Miniconda3-latest-Linux-x86_64.sh` and `source ./Miniconda3-latest-Linux-x86_64.sh` is unimportant in this context because there isn't a dependence on inherited environment variables. I still changed it to the call with `bash` to be more consistent with their instructions.

More importantly, I updated the section to explicitly mention to close/re-open the terminal. This is important for changes to take effect.
